Chapter/parallel computing completed
MonashDeepNeuron/HPC-Training pull request #13
Opened 2023-03-26 03:37 UTC by UnciaBit

# Details

Parallel Computing section is complete. I've removed the "shared memory" section as it is merged in "What is parallel computing" section.

# Linked Issues

#6

2023-03-26 22:39 UTC, oraqlle requested changes
Overall pretty good. I would like you to try and focus more on the general concept of parallel computing in general (threads, multicore CPU) and ignore OpenMP in the beginning because it is a specific parallel architecture ie. save it for a specific section later. 

Similarly you don't need to mention distributed computing, distributed memory architectures or Slurm. These topics are covered in the next and previous chapters respectively.

With the challenges, I want to have some be more conceptual/theory like:
 
- How you parallelize a reduction?
 - What invariants must you uphold for this to work for any binary operator (associativity and commutative) etc. 

and then some that are coding tasks like:

- Create a C program that sums the numbers in a array from a file
- Run on you local machine
- Log into M3
- Copy you file (maybe some SSH/SCP can be done for this as a bonus skill)
- Create a Slurm job file for this program that runs on a single machine and single core/thread and measure the execution time and record it in a file
- Now create another copy and adapt the program to use OpenMP parallelism tools
- Create a new Slurm job file that runs on a single machine multiple cores/threads and measure the execution time and save to a text file.
- Is there an improvement?

Now that I think about it, we could have a GitHub template for training content that recruits can then make a copy from (not fork or clone there is an actual template option) with different files with a list of numbers with each file having a different size. This way they can clone it locally, write the original program and push the changes (Git practice), clone to M3 and write the new programs, same the results and Slurm batch files etc. in the repo which they can then save and we can "assess".

Regardless the goal is go more in depth with each topic and focus on the concepts and then give them challenges that actually make them write code for themselves with varying degrees of difficulty to get sufficiently comfortable with writing, building and running HPC programs not just building and running.

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/challenges.md
> +>[!note]
Make sure the Markdown is correct otherwise it won't render correctly. `>` means quote block and `[]()` is a link.

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/multithreading.md
> +command: `show_cluster`
Try and use code blocks with with three backticks. eg.

In markdown

<pre lang="no-highlight"><code>```sh
cat file.txt
```
</code></pre>

which renders as:

```sh
cat file.txt
```

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/multithreading.md
> +![](src/chapter4/_attachments/Pasted%20image%2020230326141406.png)
Maybe save images to `imgs/` directory. You can also use relative paths rather than the absolute path. I also then the image needs a label/name.

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/openmp.md
> +-   Source codes with “#” provide additional information to compiler
The preprocessor will be discussed in the C section. I recommend discussion more about how it is `#pragma` are used as compiler specific preprocessor directives and then go into what it does a bit more.

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/parallel-computing.md
> +In some cases, the steps required to solve the problem can be executed simultaneously (in parallel) rather than serially (in order)
serial -> sequential

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/parallel-computing.md
> +There is shared memory architectures where multiple CPUs runs on the same server. OpenMP uses this model
Try putting text above images, I find it is easier to read in most cases.

2023-03-26 22:39 UTC, oraqlle commented on src/chapter4/parallel-computing.md
> +**Distributed Memory Architecture:**
You should use `#` for headings and not emphasis markers.

2023-03-27 00:55 UTC, UnciaBit commented
Thanks for the review, I didn't actually attempt compiling the mdBook before I made the PR, and I should've done it earlier because I can see a lot of things breaking/feature not existing in mdBook.

The contents are ripped straight off the presentation slides with no additional details added - I will add the contents you have mentioned moving forwards .

> Log into M3
> Copy you file (maybe some SSH/SCP can be done for this as a bonus skill)
> Create a Slurm job file for this program that runs on a single machine and single core/thread > and measure the execution time and record it in a file

I will presume that these tasks/challenges are going to be in the M3 section already, so in the parallel computing section, I will assume the reader has the knowledge to perform these tasks (maybe link to the M3 section), does that sound alright?

2023-03-27 01:27 UTC, oraqlle commented
> ... I didn't actually attempt compiling the mdBook before I made the PR, and I should've done it earlier because I can see a lot of things breaking/feature not existing in mdBook.

I figured but all good. You can have it running will editing and it will dynamically update.

> The contents are ripped straight off the presentation slides with no additional details added - I will add the contents you have mentioned moving forwards .

Awesome, I look forward to seeing what you come up with.

> I will presume that these tasks/challenges are going to be in the M3 section already, so in the parallel computing section, I will assume the reader has the knowledge to perform these tasks (maybe link to the M3 section), does that sound alright?

Yes that is correct. Everything from Slurm to loading modules is planned for the M3 chapter while multi-machine and message passing is planned for the Distributed Computing chapter. Links or even just weak references are a good idea as well. 

I'll also create the template GitHub project for the recruits now so you and @MonashDeepNeuron/hpc-training can start creating challenges in there. We can break each chapter into different directories and break those down further as need.

2023-03-27 01:32 UTC, oraqlle commented
@MonashDeepNeuron/hpc-training [HPC Training Challenges Template](https://github.com/MonashDeepNeuron/HPC-Training-Challenges) repo is up. 🚀

2023-04-16 08:30 UTC, oraqlle requested changes

2023-04-16 08:30 UTC, oraqlle commented on src/chapter4/openmp.md
> +-   Source codes with “#” provide additional information to compiler
This still hasn't been resolved

2023-04-16 08:36 UTC, oraqlle approved these changes
Looks good.

2023-04-16 08:36 UTC, merged